"""Which ``/signals`` readings are flags, and what they mean.

Generated by tools/generate_signal_booleans.py from the signal harvests
of every installation we hold. Do not edit by hand.

A signal entity is built before the signal branch has ever been polled --
the branch is not read at all while every one of its entities is disabled,
which is the normal case. So unlike a unit or a state class, which the
sensor fills in from the first reading, the *platform* a signal belongs to
has to be known before there is a reading. Hence a list rather than a
check against the live value.

A flag absent here stays a sensor reporting the word ``true`` or
``false``, which is how this list learns: a contributed diagnostics file
carries every signal with its value, and the coordinator logs any string
signal reading a flag word that this list does not name.
"""

from __future__ import annotations

from homeassistant.components.binary_sensor import BinarySensorDeviceClass

#: Signal id -> device class, or ``None`` where the id does not say
#: plainly enough what the flag means.
BOOLEAN_SIGNALS: dict[str, BinarySensorDeviceClass | None] = {
    "/signals/SC.DHW1.HolidayAutoTD": None,
    "/signals/SC.HC1.RTSD.PreventionEcoModeActive": None,
    "/signals/SC.HC2.RTSD.PreventionEcoModeActive": None,
    "/signals/SRC.AirPurgeModeActive": BinarySensorDeviceClass.RUNNING,
    "/signals/SRC.CUHP.Additional.ExternBlocked": None,
    "/signals/SRC.CUHP.CH.ExternBlocked": None,
    "/signals/SRC.CUHP.CH.HC1PumpRelay": BinarySensorDeviceClass.RUNNING,
    "/signals/SRC.CUHP.CH.HeatingSystemVolumeFlowLow": None,
    "/signals/SRC.CUHP.Cooling.Active": BinarySensorDeviceClass.RUNNING,
    "/signals/SRC.CUHP.DHW.ExternBlocked": None,
    "/signals/SRC.CUHP.HMI.AddElectricActive": BinarySensorDeviceClass.HEAT,
    "/signals/SRC.CUHP.HMI.BuzzerActive": None,
    "/signals/SRC.CUHP.HMI.CompressorActive": BinarySensorDeviceClass.RUNNING,
    "/signals/SRC.CUHP.HP1.Additional.AlarmInput": BinarySensorDeviceClass.PROBLEM,
    "/signals/SRC.CUHP.HP1.BrineTempHeatingLow": None,
    "/signals/SRC.CUHP.HP1.CHPumpRelay": BinarySensorDeviceClass.RUNNING,
    "/signals/SRC.CUHP.HP1.CollectorCircuitPressureSwitch": None,
    "/signals/SRC.CUHP.HP1.CompressorExtBlocked": None,
    "/signals/SRC.CUHP.HP1.CompressorStatus": BinarySensorDeviceClass.RUNNING,
    "/signals/SRC.CUHP.HP1.CrankcaseHeater": BinarySensorDeviceClass.HEAT,
    "/signals/SRC.CUHP.HP1.DHWHeater": BinarySensorDeviceClass.HEAT,
    "/signals/SRC.CUHP.HP1.DHWValve": BinarySensorDeviceClass.RUNNING,
    "/signals/SRC.CUHP.HP1.DripPanHeater": BinarySensorDeviceClass.HEAT,
    "/signals/SRC.CUHP.HP1.ElectricalHeaterStep1": BinarySensorDeviceClass.HEAT,
    "/signals/SRC.CUHP.HP1.ElectricalHeaterStep2": BinarySensorDeviceClass.HEAT,
    "/signals/SRC.CUHP.HP1.ElectricalHeaterStep3": BinarySensorDeviceClass.HEAT,
    "/signals/SRC.CUHP.HP1.ElectricalHeaterStep4": BinarySensorDeviceClass.HEAT,
    "/signals/SRC.CUHP.HP1.FourwayValve": BinarySensorDeviceClass.RUNNING,
    "/signals/SRC.CUHP.HP1.G3Relay": BinarySensorDeviceClass.RUNNING,
    "/signals/SRC.CUHP.HP1.HeatUpSequence": BinarySensorDeviceClass.RUNNING,
    "/signals/SRC.CUHP.HP1.HeatingCable": BinarySensorDeviceClass.HEAT,
    "/signals/SRC.CUHP.HP1.HighOutdoorTempStopCooling": None,
    "/signals/SRC.CUHP.HP1.HighOutdoorTempStopHeating": None,
    "/signals/SRC.CUHP.HP1.HighestPermittedAirTemp": None,
    "/signals/SRC.CUHP.HP1.HighestPermittedTemp": None,
    "/signals/SRC.CUHP.HP1.InverterOverheated": BinarySensorDeviceClass.PROBLEM,
    "/signals/SRC.CUHP.HP1.LowOutdoorTempStopCooling": None,
    "/signals/SRC.CUHP.HP1.LowOutdoorTempStopHeating": None,
    "/signals/SRC.CUHP.HP1.LowestPermittedAirTemp": None,
    "/signals/SRC.CUHP.HP1.LowestPermittedFlowTemp": None,
    "/signals/SRC.CUHP.PC0ConnectedToLIN": BinarySensorDeviceClass.CONNECTIVITY,
    "/signals/SRC.CUHP.PC1ConnectedToLIN": BinarySensorDeviceClass.CONNECTIVITY,
    "/signals/SRC.CUHP.PC2ConnectedToLIN": BinarySensorDeviceClass.CONNECTIVITY,
    "/signals/SRC.CUHP.SilentModeActive": None,
    "/signals/SRC.IntDHW.CircPumpStatus": BinarySensorDeviceClass.RUNNING,
    "/signals/SRC.IntDHW.DHURunning": BinarySensorDeviceClass.RUNNING,
    "/signals/SRC.IntDHW.ExtraActive": None,
    "/signals/SRC.RelayStatus.3WayValve": BinarySensorDeviceClass.RUNNING,
    "/signals/SRC.RelayStatus.CHPump": BinarySensorDeviceClass.RUNNING,
    "/signals/SRC.RelayStatus.Fan": BinarySensorDeviceClass.RUNNING,
    "/signals/SRC.RelayStatus.GasValve1": BinarySensorDeviceClass.RUNNING,
    "/signals/SRC.RelayStatus.GasValve2": BinarySensorDeviceClass.RUNNING,
}
